### ISSUE TITLE
"Error: unknown type: bool" when using makeStructuredView() with stuct with bool

### ISSUE THREAD

**Issue by edelmanjm** [greggman/webgpu-utils#5]
Me again. I seem to be having trouble when trying to use `makeStructuredView()` with a struct with the following definition:

```
struct my_struct {
	my_bool: bool,
}
```

[Here's a JSFiddle that reproduces](https://jsfiddle.net/epk5oLx1/5/). I believe bools are valid struct members since they're scalar types; am I missing something?

**Comment by greggman** [comment]
Looks like a bug. I'll try to fix

**Comment by greggman** [comment]
actually, AFAIK, no, you can't put bool in anything you'd use this for

https://jsgist.org/?src=9040e8c19d287d69d83c8837370e42fa

**Comment by greggman** [comment]
They are valid struct members but at the moment you could only use them in a struct that appears internally in WGSL, not one used to pass data via buffers

**Comment by edelmanjm** [comment]
Gotcha, thanks.
