### ISSUE TITLE
Type ShaderDataDefinitions does not have export symbols

### ISSUE THREAD

**Issue by BlackdBlook** [greggman/webgpu-utils#8]
Hello！
 I noticed that the type ShaderDataDefinitions in this library does not have an export symbol. Is this an oversight or intentional? 
![image](https://github.com/greggman/webgpu-utils/assets/47099583/bf9bd3f8-935e-42f1-8d1c-f205682c2bfd)

 Can this be fixed? Thank you.

**Comment by greggman** [comment]
at the moment it's intentional. It's meant to be opaque to pass to other functions. What are you trying to do?

**Comment by BlackdBlook** [comment]
I am learning to use this library to implement the Material encapsulation of my engine, trying to make setting Uniform variables as simple as OpenGL glUniform1i(). Therefore, I have considered caching this part of the content as an attribute in a certain type or passing it as a parameter, but Typescript will consider this type as undefined, which can be a bit troublesome.To achieve this functionality, I had to declare an identical type in my file and add an export symbol ,there might be a better way, as I am not a skilled JavaScript programmer,If there is a better solution, please let me know. I would greatly appreciate it..

**Comment by greggman** [comment]
ok, I exported it in v1.6.0

**Comment by BlackdBlook** [comment]
looks good, thank you
